### ISSUE TITLE
exam

### ISSUE THREAD

**Issue by PMC27** [chickma1/CS230-Project#10]
Does anyone have the files downloaded from tanner's webpage? Csee systems have been down today

**Comment by dustinteel** [comment]
I was wondering the same thing. I'm freaking out lol

On Monday, October 5, 2015, PMC27 <notifications@github.com> wrote:

> Does anyone have the files downloaded from tanner's webpage? Csee systems
> have been down today
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/10>.
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
Let me know if it comes up or someone finds the notes. I haven't done any studying yet cause it's been down.

**Comment by PMC27** [comment]
Exam on thurs now so all is good
