### ISSUE TITLE
Sprint Deliverable

### ISSUE THREAD

**Issue by chickma1** [chickma1/CS230-Project#11]
Okay everyone, the goal is to get the first sprint deliverable finished by tuesday so we can look over it and change stuff that needs changing. In class today, we assigned parts of the deliverable that each of us need to complete:
Me: Use-Case Diagram
Fleming and Dustin: Scenarios
Josh: Context Diagram
James: #1 Introduction (look at example on her website)
Phillip: #2 General Description (look at example on her website)

If there are any issues let me know

**Comment by jhyattwvu** [comment]
OK we need to decide on a name
I thought of      WVUvote, UniVote,
ones from phil   VoteNight, VoteRight, Vote or Else

**Comment by dustinteel** [comment]
I like UniVote and VoteRight
