### ISSUE TITLE
System Evolution

### ISSUE THREAD

**Issue by fleming333** [chickma1/CS230-Project#14]
I have finished the system evolution. It might need some editing so if you guys can go take a look, that would be grand. I uploaded it to the google drive.

**Comment by PMC27** [comment]
Is there anything that needs to be done that isn't?

**Comment by dustinteel** [comment]
I don't think so but someone please correct me if I'm wrong. Is it all put
together?

On Wednesday, November 4, 2015, PMC27 <notifications@github.com> wrote:

> Is there anything that needs to be done that isn't?
>
>
> > On Nov 4, 2015, at 1:12 PM, fleming333 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I have finished the system evolution. It might need some editing so if
> you guys can go take a look, that would be grand. I uploaded it to the
> google drive.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153893599>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
I have all of it put together except the system evolution and class diagram. I can add the system evolution now but we need the class diagram

**Comment by chickma1** [comment]
Alright I put up the almost finished sprint deliverable

**Comment by dustinteel** [comment]
Is there anyone who can do the class diagram? I have a Mac and I can't use
Visio

On Wednesday, November 4, 2015, chickma1 <notifications@github.com> wrote:

> Alright I put up the almost finished sprint deliverable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153928107>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Phillip, James, or Josh, could one of you try to get the class diagram done?

**Comment by jtsimons898** [comment]
I can do it if no one is yet

**Comment by chickma1** [comment]
Thanks man. Dustin, how are we turning this in?

**Comment by dustinteel** [comment]
That would be awesome. If I had Visio or was close to campus right now I
would give it a shot. I'm 30 minutes away right now visiting my boyfriend

On Wednesday, November 4, 2015, jtsimons898 <notifications@github.com>
wrote:

> I can do it if no one is yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153932448>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by dustinteel** [comment]
We have to print it out. I'll check in the morning on drive add in the
class diagram and print it out before I leave for my first class.

On Wednesday, November 4, 2015, chickma1 <notifications@github.com> wrote:

> Thanks man. Dustin, how are we turning this in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153932988>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Alright cool. If you run in to any issues let me know cause I can print it before class as well

**Comment by dustinteel** [comment]
Will do!

On Wednesday, November 4, 2015, chickma1 <notifications@github.com> wrote:

> Alright cool. If you run in to any issues let me know cause I can print it
> before class as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153934478>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by dustinteel** [comment]
Is the class diagram finished? I went to combine and print and it's not on
the google drive. We really need this finished

On Wednesday, November 4, 2015, Dustin Teel <dlteel@mix.wvu.edu> wrote:

> Will do!
>
> On Wednesday, November 4, 2015, chickma1 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Alright cool. If you run in to any issues let me know cause I can print
>> it before class as well
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-153934478>
>> .
>>
>
>
> --
>
> ********************************************************************************
> Dustin L. Teel
>
> Undergraduate
> Lane Department of Computer Science and Electrical Engineering
> Benjamin M. Statler College of Engineering and Mineral Resources
> West Virginia University
>
> Secretary
> Gamma Delta Crescent Colony
> Delta Tau Delta
>
> Undergraduate Teaching Assistant
> Women in Movies
> Women and Gender Studies
>
> ********************************************************************************
>
>
>

-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
It should be on there. I uploaded it last night.

**Comment by jtsimons898** [comment]
Just got on the google drive and its on there. Should be named CS230ProjextClassDiagram. If you still can't see it, give me your email and I'll just send it to you.

**Comment by dustinteel** [comment]
Sorry found it I was looking for an image file  I'll have to open it during
my next class because I don't have Visio to open it.

On Thursday, November 5, 2015, jtsimons898 <notifications@github.com> wrote:

> Just got on the google drive and its on there. Should be named
> CS230ProjextClassDiagram. If you still can't see it, give me your email and
> I'll just send it to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/14#issuecomment-154068302>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jhyattwvu** [comment]
sorry i did see your message yesterday because I got back late, I uploaded the reformatted intro
