### ISSUE TITLE
Prototype Assignments

### ISSUE THREAD

**Issue by dustinteel** [chickma1/CS230-Project#15]
I forget who I assigned which part of the prototype.  Who took Add Election Commissioner and Create Ballot?  I think Fleming took one but I don't remember which

**Comment by fleming333** [comment]
Me and chad got add election commissioner

**Comment by jtsimons898** [comment]
What was I assigned?'

**Comment by dustinteel** [comment]
Hey guys just checking on progress since nothing is uploaded to blue host

On Friday, November 6, 2015, jtsimons898 <notifications@github.com> wrote:

> What was I assigned?'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/15#issuecomment-154564893>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by fleming333** [comment]
We still start this week. Sorry for the inconvenience

**Comment by PMC27** [comment]
We need to have stuff done by friday right?

**Comment by dustinteel** [comment]
They need to be finished a little before that because we need to make sure
all the pages have the same look and work together

On Monday, November 9, 2015, PMC27 <notifications@github.com> wrote:

> We need to have stuff done by friday right?
>
> Sent from my iPhone
>
> > On Nov 9, 2015, at 4:06 PM, dustinteel <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Hey guys just checking on progress since nothing is uploaded to blue host
> >
> > On Friday, November 6, 2015, jtsimons898 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > What was I assigned?'
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/chickma1/CS230-Project/issues/15#issuecomment-154564893
> >
> > > .
> > >
> >
> >
> > --
> >
> ********************************************************************************
> > Dustin L. Teel
> >
> > Undergraduate
> > Lane Department of Computer Science and Electrical Engineering
> > Benjamin M. Statler College of Engineering and Mineral Resources
> > West Virginia University
> >
> > Secretary
> > Gamma Delta Crescent Colony
> > Delta Tau Delta
> >
> > Undergraduate Teaching Assistant
> > Women in Movies
> > Women and Gender Studies
> >
> ********************************************************************************
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/15#issuecomment-155280058>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by PMC27** [comment]
Alright I should have mine up today or tomorrow at the latest. Have had issues with the internet.

**Comment by jtsimons898** [comment]
Sorry I couldn't make it to class today. Did I miss anything important?

**Comment by dustinteel** [comment]
Hey is the vote part of the website ready? It's not up

On Tuesday, November 10, 2015, jtsimons898 <notifications@github.com> wrote:

> Sorry I couldn't make it to class today. Did I miss anything important?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/15#issuecomment-155611246>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
The input election commissioner isn't completely done either. I put it up for Fleming to finish. The only thing left is to add a button to go to the homepage and a message popping up saying the ec was added. I tried to use javascript for that to test for blank text forms but it wasn't working correctly

**Comment by PMC27** [comment]
Ill have it up before class tomorrow

**Comment by fleming333** [comment]
I uploaded the election commissioner page on to google drive
