### ISSUE TITLE
Webpage 

### ISSUE THREAD

**Issue by jtsimons898** [chickma1/CS230-Project#16]
I'm currently working on the disqualify voters. Do I need to handle getting the usernames or just use fake data for now?

**Comment by dustinteel** [comment]
You need to take a username but you don't have to do anything with it

On Tuesday, November 24, 2015, jtsimons898 <notifications@github.com> wrote:

> I'm currently working on the disqualify voters. Do I need to handle
> getting the usernames or just use fake data for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/16>.
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
Ok. I'll have it up sometime tomorrow.

**Comment by jtsimons898** [comment]
I put the code of the webpage on the google drive. Can someone take a look at it? I can;t figure out how to display that the username has been disqualified when you click the submit button, The form just dissapears when you click it, and the couple different ways I tried getting the message to display didn;t work.
