### ISSUE TITLE
Final work needed to do

### ISSUE THREAD

**Issue by dustinteel** [chickma1/CS230-Project#17]
Things to do:
1. Sequence Diagrams (Dec 8)
2. Display Ballot (Dec 4)
3. Display Election Results (Dec 4)
4. Certify Election (Dec 4)
5. Recount (Dec 4)

Get Election Results and Reports <-- I think Fleming is doing this

I need everyone to choose something for this so we can get everything finished.  I'll take one of the implementations since I don't have Windows and can't use Visio

**Comment by dustinteel** [comment]
Let me know which ones you guys want to do

**Comment by jtsimons898** [comment]
I can do the recount since I'm still working on getting the disqualify page and it seems like they'll be incredibly similar.

**Comment by dustinteel** [comment]
Thanks @jtsimons898 !  Anybody else? I'm starting on the display ballot right now.

**Comment by dustinteel** [comment]
The Display Ballot part is now finished

**Comment by chickma1** [comment]
Sorry man, I've been busy as hell. I'm not trying to dodge any work. I can do the certify election one. What do the last two consist of?

**Comment by dustinteel** [comment]
We have sequence diagrams where we have to draw in visio a diagram for each
use case/scenario and  the Display ballot results which will just show the
ballot of current/upcoming elections.

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Alright we will talk about it tomorrow in class. I'll start the diagrams but the other thing is due Friday and no one is jumping on that lol

**Comment by dustinteel** [comment]
Awesome! I may have time to work on the other pages. Check out the site
when you get a chance. I finished a fake login.

Head of SO login: so
Election Commissioner login: ec
Voter login: voter

All passwords: pass

On Wednesday, December 2, 2015, chickma1 <notifications@github.com> wrote:

> Alright we will talk about it tomorrow in class. I'll start the diagrams
> but the other thing is due Friday and no one is jumping on that lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-161433433>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by dustinteel** [comment]
Ok guys let me know when your parts for the webpage are finished and where you upload them so I can integrate them with the rest of the website.  Thanks!

**Comment by jhyattwvu** [comment]
got the input ballot done

**Comment by jhyattwvu** [comment]
an a two ' out of place the screwed with me for hours

**Comment by jhyattwvu** [comment]
ok is there anything else i can do? and phil said he is not in the class

**Comment by chickma1** [comment]
Alright, i added certify, certifysgaresults, and certifysewingclub. I changed ecmain and uploaded it, it works on my computer but for some reason my certify link doesn't show up on the left side after I login in our main site

**Comment by jtsimons898** [comment]
I uploaded the disqualify votes and recount pages. I did the best I could with it, but I can;t get the form to display the way I wanted it to, and I can;t even get the recount page to display a success message. Feel free to take a look at it and then tell me in lab what I did wrong. I've spent a few hours attempting to figure this out, but I'm just completely stuck.

**Comment by dustinteel** [comment]
The inputballot.html file is empty on the website

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jhyattwvu** [comment]
really? i checked after i uploaded it

**Comment by jhyattwvu** [comment]
what happened to it?

**Comment by jhyattwvu** [comment]
i re uploaded again

**Comment by jtsimons898** [comment]
The form doesn't work now. I couldn't find a working way to get it to display fake ballot information.

**Comment by dustinteel** [comment]
Everything is uploaded except Fleming's Get Election Results and Reports. I
fixed recount and disqualify the best I could. And the form works for me
just fine. I'm heading to bed but will check this again before lab tomorrow

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by fleming333** [comment]
I got this Dustin, don't worry

**Comment by fleming333** [comment]
I finished my page and uploaded it to google drive. I couldn't figure out how to organize better so tell me how I can organize better when you see it tomorrow

**Comment by jtsimons898** [comment]
If there's anything else that still needs to be gone for today or Tuesday, let me know.

**Comment by dustinteel** [comment]
Any progress on the deliverable stuff?

On Friday, December 4, 2015, jtsimons898 <notifications@github.com> wrote:

> If there's anything else that still needs to be gone for today or Tuesday,
> let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-162005054>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Nope I'm gonna do the stuff tonight. The class diagram is almost done, I didn't start the sequence diagrams yet

**Comment by chickma1** [comment]
Alright Dustin. I put up a class diagram that's close to being done on the drive. I don't think i have that class diagram sheet actually so I hope i added everything needed. The only thing that is confusing me is that vote inherits election and ballot but it also has multiplicity but idk if i can do both at the same time

**Comment by chickma1** [comment]
And alright can someone help me with these sequence diagrams? There is a lot more scenarios then i remember. They are pretty easy its just a good bit of work for one person to do all of them

**Comment by dustinteel** [comment]
Can someone who has a Windows computer help him out with the sequence
diagrams?

On Monday, December 7, 2015, chickma1 <notifications@github.com> wrote:

> And alright can someone help me with these sequence diagrams? There is a
> lot more scenarios then i remember. They are pretty easy its just a good
> bit of work for one person to do all of them
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-162679787>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
There are 9 total, if someone does the last 4 ill do the first 5

**Comment by chickma1** [comment]
Dustin, am i going off the scenarios or how our website actually works...and if the user has the option to chose certify, disqualify, or recount, how would i put an or in a sequence diagram

**Comment by dustinteel** [comment]
Go off the scenarios. And I'd say leave those alternative routes off

On Monday, December 7, 2015, chickma1 <notifications@github.com> wrote:

> Dustin, am i going off the scenarios or how our website actually
> works...and if the user has the option to chose certify, disqualify, or
> recount, how would i put an or in a sequence diagram
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-162686984>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Ight

**Comment by chickma1** [comment]
I uploaded certify in a new folder. Can you check it when you get a chance. You can just crop out the name when you add it to the document

**Comment by chickma1** [comment]
Im putting them up as I go so you can let me know if i need to add anything or not

**Comment by dustinteel** [comment]
They look good so far!

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by dustinteel** [comment]
Also guys remember you have to submit the following individually tomorrow:

1.  Individual project legacy
2.  Individual Final Report

See Final Project Deliverable
<http://www.cs.wvu.edu/~tanner/cs230/FinalProjectDeliverable.doc> to see
what those consist of.  If you don't turn those in it will affect your
individual grade on the project

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Were not putting Philip on there right lol

**Comment by dustinteel** [comment]
Nooooo lol

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Aright they should all be up on the drive. Again, i feel like some might be missing something so let me know and its an easy fix. If you need me to help you with anything else just let me know and i will

**Comment by dustinteel** [comment]
I'm looking at the class diagram now.

An election should "have" ballots and votes.  Votes do not have elections.

So, election should be connected to ballot with an arrow pointing at
election. 1 should be on the end with an arrow and a 1 on the other end too.

Vote should be connected to election with an arrow pointing towards
election with a 1 on the end with the arrow and 0...* on the other end.  It
should be connected to student as well with an arrow pointing to student.
It should have 0...* on the side with the arrow and 1 on the other side.

Head of Student Organizations should have a username, not organization.

Ballot should have race names, candidates, candidate parties,

Election should have Election name, start time, end time, start day , end
day, and eligibility rules.

I think that about covers it.  Let me know if you don't understand what I
am saying lol


********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Shit sorry I fell asleep early. I'm fixing it right now

**Comment by chickma1** [comment]
So vote doesn't have any members?

**Comment by dustinteel** [comment]
Sorry vote should be connected to student with an arrow pointing towards
student. 1 on the arrow side and a 0...* on the other side.

On Tuesday, December 8, 2015, chickma1 <notifications@github.com> wrote:

> So vote doesn't have any members?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-162895220>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
Alright so vote has no members?

**Comment by dustinteel** [comment]
the ones you have already are fine just add student username to it and it's
good

On Tuesday, December 8, 2015, chickma1 <notifications@github.com> wrote:

> Alright so vote has no members?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/17#issuecomment-162897175>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
alright its up
