### ISSUE TITLE
Project Website?

### ISSUE THREAD

**Issue by jtsimons898** [chickma1/CS230-Project#5]
What is the url, username ,and password of the project website aaron gave us yesterday? I tried to see if I could access it, but I must have written it down wrong.

**Comment by dustinteel** [comment]
Lab230g7.net
User: labtwot7
Pass: &lab230G7.net

On Saturday, September 19, 2015, jtsimons898 <notifications@github.com>
wrote:

> What is the url, username ,and password of the project website aaron gave
> us yesterday? I tried to see if I could access it, but I must have written
> it down wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/5>.
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************
