### ISSUE TITLE
Interview Questions

### ISSUE THREAD

**Issue by dustinteel** [chickma1/CS230-Project#6]
Hey guys check out the interview questions with order and let me know what you think

-Dustin

**Comment by chickma1** [comment]
Do we need to add more interview questions? I know we have a lot already but do we need some for each of the stakeholders?

**Comment by dustinteel** [comment]
I think as long as we have enough to last the 35 minutes we'll be ok. We
can't possibly ask questions to like 20 stakeholders in just 30 minutes.

On Wednesday, September 23, 2015, chickma1 <notifications@github.com> wrote:

> Do we need to add more interview questions? I know we have a lot already
> but do we need some for each of the stakeholders?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/6#issuecomment-142608916>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
I agree I was just checking. Well they look good to me then. I guess the next step is to split up the questions somehow so everyone asks something

**Comment by dustinteel** [comment]
Let me format it looking nice so I can take it to her tomorrow. You can
help spilt up the questions if you want

On Wednesday, September 23, 2015, chickma1 <notifications@github.com> wrote:

> I agree I was just checking. Well they look good to me then. I guess the
> next step is to split up the questions somehow so everyone asks something
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/6#issuecomment-142721713>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by dustinteel** [comment]
Check out the interviewquestions.docx in the deliverables folder.  Suggest changes/edits here before tonight at midnight.  I'm turning them in to Tanner tomorrow morning.

**Comment by chickma1** [comment]
It looks good to me. Everyone else needs to make sure to read over these and be prepared for Friday. I think it will be a good idea to record the interview on Friday as well as taking notes. Just so we don't miss out on anything that the "stakeholders" say

**Comment by dustinteel** [comment]
Hey guys! Don't forget our interview is scheduled for 3:20-3:55 today. I'll bring copies of the questions. Don't forget to dress up and try to be there by three so we can get everything in order.

**Comment by fleming333** [comment]
I'll be there by three

**Comment by chickma1** [comment]
Alright i did miss this, number one is answered in the project description

**Comment by dustinteel** [comment]
Oh, wow.  And I read the description a few times.  I completely missed it.
Sorry about that

********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
its all good. Its not your fault i should have caught it wednesday

**Comment by chickma1** [comment]
Alright i took that out, added in number 9, and re formatted. Im trying to think of some more questions because i was told she might give one word answers which could shorten the interview

**Comment by dustinteel** [comment]
Ok I'm in the lab in AERB if you're on campus

On Friday, September 25, 2015, chickma1 <notifications@github.com> wrote:

> Alright i took that out, added in number 9, and re formatted. Im trying to
> think of some more questions because i was told she might give one word
> answers which could shorten the interview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/6#issuecomment-143306794>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
Ill add something if I think of any additional questions to ask

**Comment by chickma1** [comment]
I'm in the library. I'm meeting with another group right now

**Comment by jhyattwvu** [comment]
I'm in the library I will be preparing reread it again

**Comment by chickma1** [comment]
Lets just try to brainstorm a couple more questions. Maybe for another stakeholder. I would but i have this group work to do

**Comment by fleming333** [comment]
I'm looking over the questions too but I suck at this asking questions thing lol

**Comment by dustinteel** [comment]
Only the stakeholders that were on the paper I turned in yesterday will "be
there"

On Friday, September 25, 2015, fleming333 <notifications@github.com> wrote:

> I'm looking over the questions too but I suck at this asking questions
> thing lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/6#issuecomment-143311472>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by chickma1** [comment]
gotcha

**Comment by fleming333** [comment]
Oh I see, Well idk what else we can ask the provost

**Comment by dustinteel** [comment]
Added a few more that I thought of

**Comment by jtsimons898** [comment]
It's 3 and I'm at the AERB. Where is everyone else?

**Comment by dustinteel** [comment]
In the lab, 138
