### ISSUE TITLE
Additional Interview & Product Backlog

### ISSUE THREAD

**Issue by dustinteel** [chickma1/CS230-Project#8]
Are we going to meet today after class or Thursday after class?  Who is able to go to office hours after class today to ask questions to the OIT and Student Records so that we have all the information we need?

**Comment by chickma1** [comment]
I'm free after class for a little bit to go to her office. When are her office hours? Do you have questions in mind?

**Comment by dustinteel** [comment]
Nothing specific yet.  Her hours are 1-1:50

**Comment by chickma1** [comment]
Alright well i'm good to meet

**Comment by dustinteel** [comment]
We are going to meet after class Thursday to complete the product backlog.
Please look over the example online and come up with some ideas before
then. See ya then!

On Tuesday, September 29, 2015, chickma1 <notifications@github.com> wrote:

> Alright well i'm good to meet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/8#issuecomment-144091297>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
I have two classes after our 230 class so I can't meet then on Thursday.

**Comment by jtsimons898** [comment]
I wouldn't be free Thursday until at least 4.

**Comment by jtsimons898** [comment]
Has no one seen my comments? I can't meet after class tomorrow.

**Comment by dustinteel** [comment]
We'll fill you in and find a time to meet as an entire group. Would you
send all times you're available?

On Wednesday, September 30, 2015, jtsimons898 <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Has no one seen my comments? I can't meet after class tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chickma1/CS230-Project/issues/8#issuecomment-144507737>
> .
>


-- 
********************************************************************************
Dustin L. Teel

Undergraduate
Lane Department of Computer Science and Electrical Engineering
Benjamin M. Statler College of Engineering and Mineral Resources
West Virginia University

Secretary
Gamma Delta Crescent Colony
Delta Tau Delta

Undergraduate Teaching Assistant
Women in Movies
Women and Gender Studies
********************************************************************************

**Comment by jtsimons898** [comment]
My last class today ends at 3:45. Also., I'm free anytime before our lab tomorrow.
